# SPDX-License-Identifier: Apache-2.0
name-template: 'NEURALWARE-X v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Breaking Changes'
    labels: ['breaking-change']
  - title: 'Features'
    labels: ['feature', 'enhancement']
  - title: 'Bug Fixes'
    labels: ['bug', 'fix']
  - title: 'Docs'
    labels: ['documentation']
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels: ['breaking-change']
  minor:
    labels: ['feature', 'enhancement']
  patch:
    labels: ['fix', 'bug', 'security']
template: |
  ## Changes
  $CHANGES
