# SPDX-License-Identifier: Apache-2.0
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: { name: nwx-serve }
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: nwx-serve }
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }
