# SPDX-License-Identifier: Apache-2.0
name: changelog-gate
on:
  pull_request:
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - run: bash tools/changelog_gate.sh origin/${{ github.base_ref }}
