# SPDX-License-Identifier: Apache-2.0
name: ci-build
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-matrix:
  if: startsWith(matrix.os, 'ubuntu') || vars.ENABLE_FULL_MATRIX == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Release, RelWithDebInfo]
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
      - name: Install deps (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build clang lld gcovr
      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DNWX_ENABLE_TESTS=ON
      - name: Build
        run: cmake --build build -j
      - name: Test
        run: |
          if [ \"${{ vars.ENFORCE_TESTS }}\" = \"true\" ]; then ctest --test-dir build --output-on-failure; else ctest --test-dir build --output-on-failure || true; fi
