
name: ci-build-ccache
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 500M
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build
      - name: Configure with ccache
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DNWX_ENABLE_TESTS=ON -DCMAKE_TOOLCHAIN_FILE=cmake/Toolchains/ccache.cmake
      - name: Build
        run: cmake --build build -j
      - name: Test
        run: ctest --test-dir build --output-on-failure
