# SPDX-License-Identifier: Apache-2.0
name: Coverage
on:
  workflow_dispatch:
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install gcovr
        run: pipx install gcovr || pip install --user gcovr
      - name: Build with coverage
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DNWX_ENABLE_COVERAGE=ON
      - name: Build
        run: cmake --build build --parallel
      - name: Test
        run: ctest --test-dir build --output-on-failure
      - name: Generate coverage
        run: gcovr -r . --exclude tests --xml build/coverage.xml --html-details build/coverage.html || gcovr -r . --exclude tests --xml coverage.xml --html-details coverage.html
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            build/coverage.xml
            build/coverage.html
            coverage.xml
            coverage.html
