# SPDX-License-Identifier: Apache-2.0
name: size-threshold
on:
permissions:
  contents: read
  id-token: none
  actions: read
  pull_request:
jobs:
  size:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python3 tools/size_threshold.py
        env:
          SIZE_GROWTH_MAX_PCT: "15"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
