# SPDX-License-Identifier: Apache-2.0
name: trufflehog
on:
permissions:
  contents: read
  id-token: none
  actions: read
  pull_request:
  push:
    branches: [ main ]
jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: trufflesecurity/trufflehog@v3.82.9
        with:
          path: ./
          base: HEAD~1
          head: HEAD
          extra_args: --only-verified

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
