# SPDX-License-Identifier: Apache-2.0
name: actionlint
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://rhysd/actionlint:latest
        with:
          args: -color -shellcheck= -ignore 'SC[0-9]+'
