# SPDX-License-Identifier: Apache-2.0
name: benchmarks
on:
permissions:
  contents: read
  id-token: none
  actions: read
  pull_request:
  push:
    branches: [ main ]
jobs:
  bench:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y libbenchmark-dev
      - run: cmake -S benchmarks -B build-bench -G Ninja
      - run: cmake --build build-bench -j2
      - run: ./build-bench/nwx_bench --benchmark_min_time=0.1 --benchmark_format=console || true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
