# SPDX-License-Identifier: Apache-2.0
name: checkov-iac
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: kubernetes,helm,terraform
          soft_fail: true
