# SPDX-License-Identifier: Apache-2.0
name: clang-format
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: |
          sudo apt-get update && sudo apt-get install -y clang-format
          diff -u <(git ls-files '*.[ch]' '*.[ch]pp' '*.[ch]xx' '*.cc' '*.cpp' | xargs -r clang-format -style=file) <(git ls-files '*.[ch]' '*.[ch]pp' '*.[ch]xx' '*.cc' '*.cpp' | xargs -r cat) || (echo "Formatting differs. Run 'make format'."; exit 2)
