# SPDX-License-Identifier: Apache-2.0
name: Container
on:
  workflow_dispatch:
  push:
    branches: [ main ]
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.distroless
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/neuralwarex:latest

  sign:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: sigstore/cosign-installer@v3
      - name: Sign image
        run: cosign sign --yes ghcr.io/${{ github.repository_owner }}/neuralwarex:latest

- name: Scan pushed image with Trivy (optional)
  uses: aquasecurity/trivy-action@0.24.0
  with:
    scan-type: 'image'
    image-ref: ghcr.io/${{ github.repository }}:latest
    ignore-unfixed: true
    severity: 'CRITICAL,HIGH'
