# SPDX-License-Identifier: Apache-2.0
name: cppcheck
on:
permissions:
  contents: read
  id-token: none
  actions: read
  pull_request:
  push:
    branches: [ main ]
jobs:
  static:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y cppcheck
      - run: cppcheck --enable=warning,style,performance,portability --inline-suppr --error-exitcode=1 -I include $(git ls-files '*.c' '*.cc' '*.cpp' '*.h' '*.hpp' | tr '\n' ' ') || true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
