# SPDX-License-Identifier: Apache-2.0
name: dco
on:
  pull_request:
jobs:
  signoff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Verify DCO
        run: |
          commits=$(git rev-list --no-merges origin/${{ github.base_ref }}..HEAD)
          fail=0
          for c in $commits; do
            if ! git log -1 --pretty=%B $c | grep -qi "Signed-off-by:"; then
              echo "Commit $c missing Signed-off-by"; fail=1
            fi
          done
          exit $fail
