# SPDX-License-Identifier: Apache-2.0
name: Docs
on:
  push:
    branches: [ main ]
jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen
      - name: Generate docs
        run: doxygen Doxyfile
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-html
          path: docs/doxygen/html
