# SPDX-License-Identifier: Apache-2.0
name: k6-thresholds
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  k6:
    runs-on: ubuntu-latest
    if: ${{ hashFiles('loadtest/k6.js') != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/k6-action@v0.3.1
        with:
          filename: loadtest/k6.js
