# SPDX-License-Identifier: Apache-2.0

name: sync-labels
on:
  push:
    paths: [".github/labels.yml"]
  workflow_dispatch:
jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml-file: .github/labels.yml
          skip-delete: true
