# SPDX-License-Identifier: Apache-2.0
name: macos-build
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build -j2
      - run: ctest --test-dir build --output-on-failure || true
