# SPDX-License-Identifier: Apache-2.0
name: markdownlint
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md
            !site/**
