# SPDX-License-Identifier: Apache-2.0
name: SBOM
on:
  push: { branches: [ main ] }
  workflow_dispatch:
jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anchore/sbom-action@v0
        with:
          path: .
          format: cyclonedx-json
          output-file: sbom.json
      - uses: actions/upload-artifact@v4
        with: { name: sbom, path: sbom.json }
