# SPDX-License-Identifier: Apache-2.0
name: slsa-provenance
on:
  release:
    types: [published]
permissions:
  id-token: write
  contents: read
jobs:
  provenance:
    runs-on: ubuntu-latest
    steps:
      - uses: slsa-framework/slsa-github-generator/actions/generator@v2.0.0
        with:
          slsa-version: v1
          upload-assets: true
